version: '3.7'
services:
  db:
    image: postgres:16.2
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro